# Generated by Django 3.2.5 on 2021-08-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_app', '0002_variation'),
        ('Carts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(to='Store_app.Variation'),
        ),
    ]
